[post-start]
cp_ghostty_submodule = "rm -rf ghostty && cp -r {{ primary_worktree_path }}/ghostty . && echo 'gitdir: {{ primary_worktree_path }}/.git/modules/ghostty' > ghostty/.git"
copy = "wt step copy-ignored"
